services:
  mockup:
    build:
      context: .
      dockerfile: Dockerfile
    image: smartcctv-net48-mockup:latest
    container_name: smartcctv-net48-mockup
    ports:
      - "127.0.0.1:8086:8080"
    restart: unless-stopped
